<h2>TERMS AND CONDITIONS OF USING INDIADOCTORS.ORG</h2>
<ol><li>INDIADOCTORS.ORG is an educationally oriented website aimed at Doctors and Medical students in India with its  office at No 6 Pillayar koil street, Padikuppam Road, Chennai, 600107.</li>
<li>If you become a member of INDIADOCTORS.ORG, a contract between you and INDIADOCTORS.ORG, incorporating these Terms and Conditions, and the indiadoctors.org privacy policy will come into force. INDIADOCTORS.ORG may refuse to accept anyone as a member, without giving any reason</li>
<li>INDIADOCTORS.ORG reserves the right at any time to add to, change or delete from the services it provides and the facilities available via this site (the INDIADOCTORS.ORG services).</li>
<li>In return for INDIADOCTORS.ORG providing access to this site and to the INDIADOCTORS.ORG services, you agree to comply with these Terms and Conditions, the INDIADOCTORS.ORG privacy policy, and all other documents referred to therein.</li>
<li>INDIADOCTORS.ORG may change these Terms and Conditions or its Privacy Policy (or both) at any time without notice, either by publishing the change or the amended version on this site or by sending it to you by email. The change will be effective as from the date of the posting or email.</li>
<li>INDIADOCTORS.ORG aims to make this site and INDIADOCTORS.ORG services available 24 hours a day, 7 days a week, but reserves the right to suspend access to this site and any or all of those services at any time, without notice, for maintenance purposes, or if INDIADOCTORS.ORG suspects that there has been any breach of security, a breach of  these Terms and Conditions, or any unlawful use of this site or those services. INDIADOCTORS.ORG may, at its discretion, restrict the use of this site and any or all of the INDIADOCTORS.ORG services, or limit their availability</li>
<li>Access to and use of some INDIADOCTORS.ORG services will be conditional on you meeting the criteria of registration with the Indian Medical Council. In some cases Hospital human resources will be allowed access to a specific part of the website  for encouraging specific posts which is of benefit to the users. INDIADOCTORS.ORG reserves the right, at its discretion, to introduce new criteria and to change any criteria from time to time. Doctors who have been removed from the Indian Medical Council register may be denied access to this site and any of the INDIADOCTORS.ORG services</li>
<li>INDIADOCTORS.ORG plans to offer benefits in the form of credit points based on the contribution and number of times of login into the website which can be redeemable in the form of vouchers or gifts or other means(no cash) decided by INDIADOCTORS.ORG  yearly once subject to availability of sponsors.</li>
<li>The above said benefits can be withdrawn at anytime or for any specific user and it is entirely upto INDIADOCTORS.ORG decision</li>
<li>INDIADOCTORS.ORG reserves the right to introduce new terms and conditions and alter existing terms and conditions including charging any specific service contained in the website or newly included feature or service in the future. A 2 weeks notice will be given to the users to that end.</li>
<li>INDIADOCTORS.ORG reserves the right to remove material without notice from this site and from any forum, and INDIADOCTORS.ORG does not undertake to keep or make available any material that you have posted or anyone else has posted to this site or to any forum for any length of time, and you are advised to make a copy of any message or material that you wish to keep.</li>
<li>As a condition of receiving the INDIADOCTORS.ORG services, you agree to receive and acknowledge a regular NEWS LETTER FORTNIGHTLY distributed by email. The NEWS LETTER will contain information carefully targeted to doctors with the summary of happenings in the website.</li>
<li>Users are  expected to act in a professional and ethical manner, does not post any message which is disruptive or which generates complaints. Not post same or similar messages multiple times in the same forum</li>
<li>Users should not flame, hack or obtain unauthorized access to any data or system</li>
<li>Not post any message whose subject or content is unrelated to the subject matter of the newsgroup.</li>
<li>Not be involved in any criminal or unlawful activity, or post any information or material which might be legally actionable, in doing so the user is fully responsible for the activity and upon notification of the same to INDIADOCTORS.ORG such activity and material will be removed at the earliest. At no point of time INDIADOCTORS.ORG is responsible for user activity or posts. Any complaints should be immediately sent to INDIADOCTORS.ORG thru contact us section guidance.</li>
<li>Not harass any person. Harassment in this instance includes you being intimidating, threatening, abusive, hostile or otherwise offensive towards another person.</li>
<li>Not cancel or supersede any message or posting other than your own (unless authorized by INDIADOCTORS.ORG to do so)</li>
<li>Not introduce into this site or any INDIADOCTORS.ORG service, any virus, logic bomb, harmful code, trojan horse or anything else that might corrupt, damage or render inaccessible any software, data or system.</li>
<li>Not seek redress from INDIADOCTORS.ORG if you suffer loss or damage, or if you are harmed, defamed or offended by material, information, products or services which you accessed or obtained through or which were posted on this site or any INDIADOCTORS.ORG services</li>
<li>Not post or send any libellous, defamatory, obscene, derogatory, menacing, offensive, pornographic, or indecent material to this site or via any INDIADOCTORS.ORG service. (Any comments posted that imply that another member is suffering from mental illness are considered to contravene these Terms and Conditions)</li>
<li>Not discuss religious topics in any part of INDIADOCTORS.ORG</li>
<li>Obtain all necessary permissions if you use this site or any INDIADOCTORS.ORG service to receive, upload, download, display, transmit, distribute, perform or execute materials, programs or other works protected by intellectual property rights or rights of privacy or confidence</li>
<li>Obtain patient consent before posting any material on this site that includes identifiable or potentially identifiable case material</li>
<li>Comply with all applicable laws, regulations and conventions, including those related to privacy, personal data, international communications, or the export of technical data</li>
<li>Not attempt to interfere with this site or any INDIADOCTORS.ORG service or any other service. (This includes, but is not limited to, "denial of service" attacks, "flooding" sites, deliberate attempts to overload any site and attempts to "crash" any website host.); and</li>
<li>INDIADOCTORS.ORG reserves the right to delete, archive, make unavailable, modify or comment on any forum posting or thread within a forum, and to close individual fora without notice</li>
<li>INDIADOCTORS.ORG will use your personal data only in accordance with its Privacy Policy.</li>
<li>INDIADOCTORS.ORG may (but is not obliged to) monitor and record your use of this site and the INDIADOCTORS.ORG services</li>
<li>No information which is posted to this site or sent via any INDIADOCTORS.ORG service will be treated as confidential</li>
<li>INDIADOCTORS.ORG may block, delete or remove from this site and from any INDIADOCTORS.ORG service any information or other material that you have posted, sent or received at any time and without giving notice.</li>
<li>If you purchase or acquire goods or services from any third party, even if you have been directed from this site or by any INDIADOCTORS.ORG service to them, any contract entered into with that third party and any use made of its site is a matter between you and that third party. INDIADOCTORS.ORG has no liability for the quality or type of services or goods provided by any third party it may mention on this site or to whom this site may be linked. It is for you to make your own judgement about them.</li>
<li>Any opinion, advice, statement, service, offer, or information or content provided or made by any third party on this site or via any INDIADOCTORS.ORG service, or on any site to which this site is linked, is that of the author or provider, and not of INDIADOCTORS.ORG. INDIADOCTORS.ORG does not endorse, and it is not responsible for, the accuracy or reliability of, any such opinion, advice, statement, service, offer, information or content.</li>
<li>Where content or information on or services available via this site or any INDIADOCTORS.ORG service have been supplied by a third party, INDIADOCTORS.ORG does not control or endorse them in any way. All information, content and services supplied by third parties are made available in good faith but INDIADOCTORS.ORG does not (to the extent allowed by the law) accept responsibility for their accuracy or use</li>
<li>INDIADOCTORS.ORG does not make any representation or give any warranty about any other site or any services or goods provided by any third party, or any opinion, advice, statement, offer, information or content on any such site or made by any such party. INDIADOCTORS.ORG has no control over their quality, content or availability. INDIADOCTORS.ORG will not be liable for any loss or damage caused by or in connection with use of, or reliance on, any content, goods or services available on or through any other site.</li>
<li>Any concern about any other website should be directed to that site's website administrator or webmaster.</li>
<li>INDIADOCTORS.ORG gives no warranty that any information or content is accurate, up to date or complete. It accepts no liability for any loss or damage caused by inaccurate information or content.</li>
<li>If you find any inaccurate, out of date or incomplete information or content on this site or in any INDIADOCTORS.ORG service, or if you suspect that something is an infringement of any intellectual property right, you must let INDIADOCTORS.ORG know immediately by contacting thru contact us section.</li>
<li>You should independently verify any information and content on this site or made available to you through any INDIADOCTORS.ORG service before relying on it. That information and content are not intended to address any particular requirements; they do not constitute any form of advice or recommendation by INDIADOCTORS.ORG and are not intended to be relied upon in making (or refraining from making) any decision. The information and content on and through this site are not, and the INDIADOCTORS.ORG services are not, substitutes for the exercise of professional judgement. If you are not qualified nor experienced enough to make that judgement, you should take professional advice</li>
<li>This site, its content and all INDIADOCTORS.ORG services are provided "as is". INDIADOCTORS.ORG gives no warranty that this site, its content or any service is free of error or will be available without interruption, or at all</li>
<li>No warranty, representation, or undertaking in respect of the quality, or fitness for purpose of any content or any service is given, and all implied terms, conditions and warranties relating to the same, whether implied by statute, common law, custom, trade usage, course of dealing or otherwise, are excluded to the extent allowed by the law.</li>
<li>You assume all risk for using, and for any results obtained, or liability incurred, by or as a result of accessing this site or any INDIADOCTORS.ORG service.</li>
<li>INDIADOCTORS.ORG is not liable for any third party's information, programs, products or services, whether or not INDIADOCTORS.ORG has negotiated special terms for the provision of the same to its members. If you access or use any information on this site that has been supplied by a third-party, you will be bound by any additional terms and conditions specified by that third party. You agree to read those additional terms and conditions before accessing or using such third party information and not to access or use that information you do not accept those additional terms and conditions. You should always read the relevant terms and conditions before accessing any information.</li>
<li>INDIADOCTORS.ORG does not guarantee the prevention of the loss of, alteration of, or improper access to, any information or computer systems. INDIADOCTORS.ORG is not responsible for invalid destinations or transmission errors in, the corruption of, or the security of information or messages on this site or transmitted using any INDIADOCTORS.ORG service or carried over any telecommunications or data communications facilities. Passwords and user IDs are personal to individual members. It is your responsibility to keep your password and ID secret and secure, and not to allow anyone else to use them. You are responsible for the use or misuse of this site and any INDIADOCTORS.ORG service by any person accessing them through your password or ID (whether that use is authorised or unauthorised) and you agree to bear all losses, expenses, inconvenience and site charges arising as a result of that use. You must not use or attempt to use anyone else's password or ID; to do so may be an offence under the Computer Misuse Acts</li>
<li>INDIADOCTORS.ORG is not liable for any claim that your access to or use of this site, any content or any INDIADOCTORS.ORG services infringes any third party's intellectual property or other rights.</li>
<li>In no event is INDIADOCTORS.ORG liable for any loss or damage arising from your failure to perform your obligations. INDIADOCTORS.ORG is not responsible for loss of profits, loss of business, loss of anticipated savings, loss of goodwill or reputation, lost or wasted management time or the lost time of other employees, Loss, destruction or corruption of data</li>
<li>Despite any other provision in these Terms and Conditions, INDIADOCTORS.ORG does not exclude or limit its liability for death or personal injury caused by its negligence, or for any fraudulent act. Subject to this, INDIADOCTORS.ORG is not liable for any of the following, whether arising because of its negligence, or in any other way</li>
<li>INDIADOCTORS.ORG  is not responsible for any indirect, or consequential loss or damage; or Any loss or damage arising as a result of any claim against you by any other party; even if INDIADOCTORS.ORG has been advised of the possibility of that loss or damage arising.</li>
<li>You will indemnify INDIADOCTORS.ORG and keep it indemnified against all and any losses, damages, liabilities, costs and expenses arising in connection with your breach of any of these Terms and Conditions or arising as a result of a third party accessing or using this site, any content or any INDIADOCTORS.ORG service by means of your password or user ID.</li>
<li>Your membership may be terminated by you or by INDIADOCTORS.ORG at any time by giving the other 7 days' notice. In addition, INDIADOCTORS.ORG may terminate or suspend your membership and access to this site and any service at any time without notice if you breach or are suspected of having breached these Terms and Conditions, if you cease to meet the criteria from time to time for access to or use of this site or any service, or if your agreement with any internet service provider for access or connection to the internet is terminated for any reason.</li>
<li>This site, its contents and information, and the INDIADOCTORS.ORG services and their content and information, are protected by copyright, database rights and other intellectual property rights. You authorise INDIADOCTORS.ORG to act on your behalf if your intellectual property rights in any material you post to this site or in any message that you send via a INDIADOCTORS.ORG service is infringed by any third party.</li>
<li>You assign to INDIADOCTORS.ORG the copyright in all material that you post to this site</li>
<li>Subject to any conditions specific to any service, you may read, print and download parts of the material and information on this site or through any INDIADOCTORS.ORG service for your private, non-commercial use or use in the ordinary course of  your profession, but you may not make any profit from the use of that material or information nor republish, disseminate or transmit any of it, or exploit it for any commercial purpose, or make any derivative work, or copy it for any other purpose without first obtaining INDIADOCTORS.ORG's written permission, or that of the rights owner.
To seek permission please contact INDIADOCTORS.ORG</li>
<li>These Terms and Conditions, and the contract between you and INDIADOCTORS.ORG, are governed by the laws of INDIA and you agree to submit to the jurisdictions of INDIA courts</li>
<li>These terms and conditions, together with the Privacy Policy, any conditions specific to any INDIADOCTORS.ORG service and any rules that INDIADOCTORS.ORG publishes from time to time governing the criteria for access to this site or any service, are the complete and exclusive statement of the agreement between INDIADOCTORS.ORG and you in relation to the use of this site, its contents and any INDIADOCTORS.ORG service. They supersede any proposal or prior agreement, oral or written, and any other communications between INDIADOCTORS.ORG and you relating to their subject matter</li>
<li>Any personal information of the user obtained by INDIADOCTORS.ORG is kept and treated highly confidential to the best of the ability, however the information obtained by INDIADOCTORS.ORG for sign up is available in the website of Medical Council of India which is open to the public, hence no loss of personal data is expected. In the event of loss of such data INDIADOCTORS.ORG is not responsible.</li>
<li>When required, users registering as doctors should send photocopies of their original medical degrees, with address proofs to INDIADOCTORS.ORG office in the event of any suspicious, illegal, fake activities in the website. Till then INDIADOCTORS.ORG has the right to suspend any users access and can take down specific users access completely without notice.</li></ol>
<li>Medical students and Human Resources personnel registering with the website should send identification documents in the form of a photocopy  or a scanned document (id badge/letter from employer) to office or email id  of indiadoctors.org ie contactus@indiadoctors.org within 3 months of the initial registration process</li>
<li>Email provision with indiadoctors.org domain is provided to users who wish to have them. For users registering as Doctors are given a maximum of 50 MB, Medical students a maximum of 25 MB, HR personnel a space of 5 MB.</li>
<li>The amount of space provision will be increased in the future subject to availability of sponsors.</li>